kind: Secret
apiVersion: v1
metadata:
  name: {{ template "chart.fullname" . }}-secret
type: Opaque
data:
{{- if .Values.appId.tenantId }}
  APP_ID_TENANT_ID: {{ required "A valid .Values.appId.tenantId entry required!" .Values.appId.tenantId | b64enc | quote }}
{{- end }}
{{- if .Values.appId.clientId }}
  APP_ID_CLIENT_ID: {{ required "A valid .Values.appId.clientId entry required!" .Values.appId.clientId | b64enc | quote }}
{{- end }}
{{- if .Values.appId.iamKey }}
  APP_ID_IAM_KEY: {{ required "A valid .Values.appId.iamKey entry required!" .Values.appId.iamKey | b64enc | quote }}
{{- end }}
{{- if .Values.appId.clientSecret }}
  APP_ID_SECRET: {{ required "A valid .Values.appId.clientSecret entry required!" .Values.appId.clientSecret | b64enc | quote }}
{{- end }}
  NEW_RELIC_LICENSE_KEY: {{ .Values.newRelic.licenseKey | b64enc | quote }}
